language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile

matrix:
  exclude:
    # rails < 3.2 is unsupported on ruby 2.0
    - rvm: 2.0.0
      gemfile: gemfiles/3.2.gemfile
